# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := CharWriterDemo
ARDUINO_LIBS := AceCommon AceTMI AceSegment AceSegmentWriter
include ../../../EpoxyDuino/EpoxyDuino.mk
